id: IB6D67A14
legacy_id: P000523
ocr_import_info:
  bdrc_scan_id: W1KG9819
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T19:00:19'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T18:39:29.406117+00:00'
last_modified: 2022-09-01 02:39:40.703930
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG9819
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG9819
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཟབ་དོན་ཐུགས་ཀྱི་སྙིང་པོ་བདུད་ཀྱི་གཅོད་ཡུལ་གྱི་སྐོར།
statistics:
  ocr_word_mean_confidence_index: 0.7699840947500869
  ocr_word_median_confidence_index: 0.8399999737739563
quality: null
bases:
  I1KG9821:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9821
      total_pages: 554
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9821.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7699840947500869
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
